# -*- coding: utf-8 -*-
"""Tokyo_olympics_sql_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxdwaIrlJSGNeTEPP9FXdzBcmv8YiYja
"""

# Installing  dependencies for ERD
!apt-get install graphviz libgraphviz-dev
!pip install eralchemy2 graphviz

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt               ### files are loaded in colab.
import sqlite3

from google.colab import files
uploaded =files.upload()

df_athletes=pd.read_excel("Athletes.xlsx")   #### athletes data frrame
df_athletes.head(3)

df_athletes.info()

df_EntriesGender=pd.read_excel("EntriesGender.xlsx")
df_EntriesGender.head(3)
df_EntriesGender.info()
df_EntriesGender.isnull().sum()                           #### EntriesGender dataframe

df_Medals=pd.read_excel("Medals.xlsx")     ### Medals dataframe
df_Medals.head(3)

df_Medals.info()
df_Medals.isnull().sum()

df_Teams=pd.read_excel("Teams.xlsx")
df_Teams.head(3)                             ### Teams dataframe
df_Teams.info()
df_Teams.isnull().sum()

df_Coaches=pd.read_excel("Coaches.xlsx")
df_Coaches.head(3)
df_Coaches.info()                                 ### Coaches dataframe
df_Coaches.isnull().sum().sum()
df_Coaches.drop(columns=["Event"], inplace=True)        ### Event column has to removed it contains majority of NaN values.

import sqlite3
connect = sqlite3.connect("Tokyo_olympics.db")  ### database formation in sql

cursor = connect.cursor()

# Drop old tables
cursor.executescript("""
DROP TABLE IF EXISTS athletes;
DROP TABLE IF EXISTS Coaches;
DROP TABLE IF EXISTS EntriesGender;
DROP TABLE IF EXISTS Medals;
DROP TABLE IF EXISTS Teams;
""")

# Create tables with proper relationships
cursor.executescript("""
CREATE TABLE Medals (
    "Team/NOC" TEXT PRIMARY KEY,
    Gold INTEGER,
    Silver INTEGER,
    Bronze INTEGER,
    Total INTEGER,
    "Rank" INTEGER,
    "Rank by Total" INTEGER
);

CREATE TABLE EntriesGender (
    Discipline TEXT PRIMARY KEY,
    Female INTEGER,
    Male INTEGER,
    Total INTEGER
);

CREATE TABLE Athletes (
    Name TEXT,
    NOC TEXT,
    Discipline TEXT,
    FOREIGN KEY (NOC) REFERENCES Medals("Team/NOC"),
    FOREIGN KEY (Discipline) REFERENCES EntriesGender(Discipline)
);

CREATE TABLE Coaches (
    Name TEXT,
    NOC TEXT,
    Discipline TEXT,
    FOREIGN KEY (NOC) REFERENCES Medals("Team/NOC"),
    FOREIGN KEY (Discipline) REFERENCES EntriesGender(Discipline)
);

CREATE TABLE Teams (
    Name TEXT,
    Discipline TEXT,
    NOC TEXT,
    Event TEXT,
    FOREIGN KEY (NOC) REFERENCES Medals("Team/NOC"),
    FOREIGN KEY (Discipline) REFERENCES EntriesGender(Discipline)
);
""")



print("Tables created with full relationships, including EntriesGender!")

# Generate ERD directly from SQLite
from eralchemy2 import render_er

# Path to your database
db_path = "Tokyo_olympics.db"

# Output file (PDF or PNG)
render_er(f"sqlite:///{db_path}", "Tokyo_olympics_erd.png")

# Display in notebook
from IPython.display import Image
Image("Tokyo_olympics_erd.png")

df_athletes.to_sql("Athletes", connect, if_exists="append", index=False) ### athletes table loaded in database
df_Coaches.to_sql("Coaches", connect, if_exists="append", index=False)  ### Coaches table loaded in database
df_EntriesGender.to_sql("EntriesGender", connect, if_exists="append", index=False) ### EnteriesGender table loaded in database
df_Medals.to_sql("Medals", connect, if_exists="append", index=False) ### Medals table loaded in database
df_Teams.to_sql("Teams", connect, if_exists="append", index=False) ### Teams table loaded in database

cursor=connect.cursor()
connect.commit()

 ### athletes table column infromation
pd.read_sql_query("""select * from athletes limit 10;""", connect)

### Coaches table column information

pd.read_sql_query("""select * from Coaches limit 3;""", connect)

pd.read_sql_query("""select * from EntriesGender limit 3;""", connect)   ### EnteriesGender table information

### whats the most frequent discipline in the table?

pd.read_sql_query(""" select count(Discipline) as Count_discipline, NOC, Discipline from Athletes
                        group by Discipline, NOC order by Count_discipline desc limit 5;""", connect)

### athletics discipline has highest count and country is USA

pd.read_sql_query("""select distinct c.Name as Coaches_name, a.Name as Athletes_name,
a.Discipline, a.NOC from Athletes a join Coaches c on a.NOC=c.NOC and
a.Discipline=c.Discipline limit 15;""", connect)    ### Athltes has multiple Coaches

### what are the count of athletes_count  and coah_count?

pd.read_sql_query(""" select  a.NOC as country, a.Discipline as discipline, count(distinct a.Name) as athletes_count,
                      count(distinct c.Name) as coach_count, ROUND(100* count(distinct c.Name) /count(distinct a.Name), 2)
                      as coaches_per_athlets_percentage
                      from Athletes a join Coaches c
                      on a.NOC=c.NOC and a.Discipline=c.Discipline
                      Group by a.NOC, a.Discipline order by coach_count desc limit 10;""", connect)

## Spain has highest number of athletes and coach.

pd.read_sql_query("""select  sum(Female) as total_female
                    from EntriesGender;""", connect)
                                                   ### total female population is 5432.

pd.read_sql_query("""select  sum(Male) as total_male
                    from EntriesGender;""", connect)  ### total male population is 5884.

### which discipline has highest female population?
pd.read_sql_query("""select Discipline, sum(Female) as total_male_in_discipline
                    from EntriesGender group by Discipline order by sum(female) desc limit 1;""", connect)
  ### Athletics discipline has highest female population : 969

### which discipline has highest male population?
pd.read_sql_query("""select Discipline, sum(Male) as total_male_in_discipline
                    from EntriesGender group by Discipline order by sum(Male) desc limit 1;""", connect)
### Athletics has highest male population: 1072

### what is the total athletes over discipline?
pd.read_sql_query("""SELECT Discipline, COUNT(Name) AS Total_Athletes
FROM Athletes
GROUP BY Discipline
ORDER BY Total_Athletes DESC
LIMIT 10;""", connect)

### show female percentage according to the discipline.

pd.read_sql_query("""SELECT Discipline, Female, Male, ROUND(Female * 100.0 / Total, 2) AS Female_Percentage
FROM EntriesGender
ORDER BY Female_Percentage DESC
LIMIT 10;""", connect)

### Artistic Swimming has the highest female population in it.

### show male percentage according to the discipline.
pd.read_sql_query("""SELECT Discipline, Female, Male, ROUND(Male * 100.0 / Total, 2) AS male_Percentage
FROM EntriesGender
ORDER BY male_Percentage DESC
LIMIT 10;""", connect)

### Wrestling has highest male population in it.

pd.read_sql_query("""select * from Medals limit 3; """, connect)  ### Medals table columns information

### what are the top ten countries that won medals?

pd.read_sql_query("""SELECT "Team/NOC" AS Country, Gold, Silver, Bronze, Total
FROM Medals
ORDER BY Gold DESC
LIMIT 10;
 """, connect)

# Top 10 countries by total medals
df_medals = pd.read_sql_query("""
SELECT "Team/NOC" AS Country, Total
FROM Medals ORDER BY Total DESC LIMIT 10;
""", connect)
df_medals

plt.figure(figsize=(10,5))
sns.barplot(data=df_medals, x="Country", y="Total")
plt.title("Top 10 Countries by Total Medals - Tokyo 2021")
plt.xticks(rotation=45)
plt.show()

df_medals = pd.read_sql_query("""
SELECT "Team/NOC" AS Country, Gold, Silver, Bronze, Total
FROM Medals
ORDER BY Total DESC
LIMIT 10;
""", connect)

df_medals.plot(
    x="Country",
    y=["Gold", "Silver", "Bronze"],
    kind="bar",
    stacked=True,
    figsize=(10,5),

)
plt.title("Top 10 Countries by Medals - Tokyo 2021")
plt.ylabel("Medal Count")
plt.xlabel("Country")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

### whats the female ratio in each countries?

pd.read_sql_query("""
SELECT a.NOC AS Country,
       SUM(e.Female) AS Total_Female,
       SUM(e.Male) AS Total_Male,
       ROUND(SUM(e.Female)*100.0/(SUM(e.Female)+SUM(e.Male)), 2) AS Female_Ratio
FROM Athletes a
JOIN EntriesGender e ON a.Discipline = e.Discipline
GROUP BY a.NOC
ORDER BY Female_Ratio DESC
LIMIT 10;
""", connect)

#  Female vs Male participation
df_gender = pd.read_sql_query("""
SELECT SUM(Female) AS Female, SUM(Male) AS Male FROM EntriesGender;
""", connect)
df_gender

plt.pie(df_gender.values[0], labels=['Female','Male'], autopct='%1.1f%%', startangle=90)
plt.title("Overall Gender Distribution in Olympics 2021")
plt.show()

### what the discipline that needed highest coach number?
pd.read_sql_query("""
SELECT Discipline,
       COUNT(DISTINCT Name) AS Coach_Count
FROM Coaches
GROUP BY Discipline
ORDER BY Coach_Count DESC
LIMIT 1;
""", connect)
### Basketball 74 coach

### what are the sports that have most Athletes?

pd.read_sql_query("""
SELECT Discipline,
       COUNT(Name) AS Athlete_Count
FROM Athletes
GROUP BY Discipline
ORDER BY Athlete_Count DESC
LIMIT 10;
""", connect)

### Athletics

# which countries are participated in olympics but did not win any medals?

pd.read_sql_query("""
SELECT DISTINCT a.NOC AS Athlete_NOC
FROM Athletes a
WHERE a.NOC NOT IN (
  SELECT DISTINCT m."Team/NOC" FROM Medals m
)
ORDER BY a.NOC;
""", connect)
 # These are countries that appear Athletes table (they sent athletes)
 # but do NOT appear in your Medals table (they didn’t win any medals).

### Show medals per country

pd.read_sql_query("""
SELECT
  a.NOC AS Country,
  COUNT(a.Name) AS Total_Athletes,
  COALESCE(m.Gold, 0) AS Gold,
  COALESCE(m.Silver, 0) AS Silver,
  COALESCE(m.Bronze, 0) AS Bronze,
  COALESCE(m.Total, 0) AS Total_Medals
FROM Athletes a
Left JOIN Medals m
  ON a.NOC = m."Team/NOC"
GROUP BY a.NOC
ORDER BY Total_Medals DESC, Total_Athletes DESC;
""", connect)

### what were the disciplines of USA?
pd.read_sql_query("""select distinct NOC, Discipline from Athletes where NOC="United States of America";""", connect)

df_us = pd.read_sql_query("""
SELECT Gold, Silver, Bronze
FROM Medals
WHERE "Team/NOC" = 'United States of America';
""", connect)

colors = ["#FFD700","#C0C0C0","#CD7F32"]
plt.figure(figsize=(5,5))
plt.pie(df_us.values[0], labels=["Gold","Silver","Bronze"], autopct="%1.1f%%", startangle=90, colors=colors)
plt.title("United States Medal Breakdown - Tokyo 2021")
plt.show()

pd.read_sql_query("""select * from Teams; """, connect) ### Teams table colum information

### Total athletes and teams per country
pd.read_sql_query("""
SELECT a.NOC AS Country,
       COUNT(DISTINCT a.Name) AS Total_Athletes,
       COUNT(DISTINCT t.Name) AS Total_Teams
FROM Athletes a
LEFT JOIN Teams t ON a.NOC = t.NOC
GROUP BY a.NOC
ORDER BY Total_Athletes DESC;
""", connect)

### Total vs Coached Athletes (Country-Level Analysis)


pd.read_sql_query("""
WITH total_athletes AS (
    SELECT
        NOC,
        COUNT(DISTINCT Name) AS Total_Athletes
    FROM Athletes
    GROUP BY NOC
),
coached_athletes AS (
    SELECT
        a.NOC,
        COUNT(DISTINCT a.Name) AS Coached_Athletes
    FROM Athletes a
    JOIN Coaches c
        ON a.NOC = c.NOC
       AND a.Discipline = c.Discipline
    GROUP BY a.NOC
)
SELECT
    t.NOC AS Country,
    t.Total_Athletes,
    COALESCE(ca.Coached_Athletes, 0) AS Coached_Athletes,
    ROUND(100.0 * COALESCE(ca.Coached_Athletes, 0) / t.Total_Athletes, 2) AS Percent_Coached
FROM total_athletes t
LEFT JOIN coached_athletes ca ON t.NOC = ca.NOC
ORDER BY t.Total_Athletes DESC
LIMIT 10;
""", connect)                                     ### Not all athletes had Coach

### Country-Level Coach-to-Athlete Ratio

pd.read_sql_query("""
SELECT a.NOC AS Country,
       COUNT(DISTINCT a.Name) AS Athletes,
       COUNT(DISTINCT c.Name) AS Coaches,
       ROUND(1.0 * COUNT(DISTINCT c.Name) / COUNT(DISTINCT a.Name), 3) AS Coach_Athlete_Ratio
FROM Athletes a
JOIN Coaches c
  ON a.NOC = c.NOC
 AND a.Discipline = c.Discipline
GROUP BY a.NOC
ORDER BY Athletes DESC
LIMIT 10;
""", connect)
                         ### Japan had the highest Coach to athlete ration

### what is the Male vs Female teams by country?

df_teams=pd.read_sql_query("""
SELECT NOC AS Country,
       SUM(CASE WHEN Event = 'Men' THEN 1 ELSE 0 END) AS Male_Teams,
       SUM(CASE WHEN Event = 'Women' THEN 1 ELSE 0 END) AS Female_Teams
FROM Teams
GROUP BY NOC
ORDER BY Female_Teams DESC;
""", connect)
df_teams                                  ### People's Republic of China	had highest number of female teams which is 9.

df_teams.plot(
    x="Country",
    kind="bar",
    stacked=True,
    color=["#1f77b4","#e91e63"],
    figsize=(12,6)
)
plt.title("Male vs Female Team Events by Country - Tokyo 2021")
plt.ylabel("Team Count")
plt.xlabel("Country")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

### country-wise medal efficiency

pd.read_sql_query("""
SELECT
  m."Team/NOC" AS Country,
  m.Gold, m.Silver, m.Bronze, m.Total,
  COUNT(DISTINCT a.Name) AS Total_Athletes,
  ROUND(1.0 * m.Total / COUNT(DISTINCT a.Name), 3) AS Medal_Efficiency
FROM Medals m
JOIN Athletes a ON a.NOC = m."Team/NOC"
GROUP BY m."Team/NOC"
ORDER BY Medal_Efficiency DESC;
""", connect)
                                 ### San Mariono hashas very few athletes but it's medal efficiency is highest.
                                 ### Althoug USA won the highest number of medal but country had more althletes.

### country wise medal per athlete and avg female participation percentage


pd.read_sql_query("""
SELECT
  a.NOC AS Country,
  COUNT(DISTINCT a.Name) AS Total_Athletes,
  COALESCE(m.Gold,0) AS Gold,
  COALESCE(m.Silver,0) AS Silver,
  COALESCE(m.Bronze,0) AS Bronze,
  COALESCE(m.Total,0) AS Total_Medals,
  ROUND(1.0*m.Total / COUNT(DISTINCT a.Name), 3) AS Medals_per_Athlete,
  ROUND(AVG(e.Female * 100.0 / e.Total), 2) AS Avg_Female_Participation
FROM Athletes a
LEFT JOIN Medals m ON a.NOC = m."Team/NOC"
LEFT JOIN EntriesGender e ON a.Discipline = e.Discipline
GROUP BY a.NOC, m.Gold, m.Silver, m.Bronze, m.Total
ORDER BY Total_Medals DESC;
""", connect)

